[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.28'
libs = ['../../node_modules', 'node_modules', 'lib']
optimizer_runs = 10_000
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read-write", path = "./deployments/" }]

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[rpc_endpoints]
mainnet = "${ETHEREUM_MAINNET_RPC}"
sepolia = "${ETHEREUM_SEPOLIA_RPC}"
fuji = "${AVALANCHE_FUJI_RPC}"
avalanche = "${AVALANCHE_MAINNET_RPC}"
gnosis = "${GNOSIS_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
gnosis = { key = "${ETHERSCAN_API_KEY}" }
